export const BLUR_DATA =
  "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAgAAAAIBAMAAABz7JzQAAAAHlBMVEUAAAD///////////////////////////////9e19sQAAAACXRSTlMABQkQWl9+u7xWg1xWAAAAC0lEQVQI12NgYGAQAAABAgABz7mJmQAAAABJRU5ErkJggg=="
